#!/usr/bin/env bash

set -Eeuo pipefail

# Remove everything generated by this example and, by default, remove its
# deployed Zarf package. This script can be run directly or by build.sh.

EXAMPLE_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
cd "$EXAMPLE_DIR"

PACKAGE_NAME="react-fastapi-postgres"
PACKAGE_NAMESPACE="react-fastapi-postgres"
CLEAN_DEPLOY="${CLEAN_DEPLOY:-true}"

OUT_DIR="$EXAMPLE_DIR/out"
PACKAGE_DIR="$EXAMPLE_DIR/packages"
LOG_DIR="$EXAMPLE_DIR/logs"
BRIDGE_TMP_DIR="$EXAMPLE_DIR/.tmp"

if [[ "$CLEAN_DEPLOY" != "true" && "$CLEAN_DEPLOY" != "false" ]]; then
  printf 'ERROR: CLEAN_DEPLOY must be true or false\n' >&2
  exit 1
fi

printf 'Removing generated build artifacts:\n'
printf '  %s\n' "$OUT_DIR" "$PACKAGE_DIR" "$LOG_DIR" "$BRIDGE_TMP_DIR"
rm -rf "$OUT_DIR" "$PACKAGE_DIR" "$LOG_DIR" "$BRIDGE_TMP_DIR"

if [[ "$CLEAN_DEPLOY" == "false" ]]; then
  printf 'Preserving the deployed package because CLEAN_DEPLOY=false\n'
elif ! command -v kubectl >/dev/null 2>&1; then
  printf 'ERROR: kubectl is required to check for the deployed package\n' >&2
  exit 1
elif kubectl get package "$PACKAGE_NAME" --namespace "$PACKAGE_NAMESPACE" >/dev/null 2>&1; then
  if ! command -v uds >/dev/null 2>&1; then
    printf 'ERROR: uds is required to remove the deployed package\n' >&2
    exit 1
  fi

  printf 'Removing deployed package: %s\n' "$PACKAGE_NAME"
  uds zarf package remove "$PACKAGE_NAME" --confirm
else
  printf 'No deployed package found: %s\n' "$PACKAGE_NAME"
fi

printf 'Clean complete.\n'
